# -*- coding: utf-8 -*-
"""DemoParity2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wfKHSGiHtG4IXcd1d36S9RKrkishaSf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Placement_Data_Full_Class.csv')

display(df.head(10))

# Quick overview
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.head())

print(df.isnull().sum())
df['salary'] = df['salary'].fillna(0)
print(df.isnull().sum())

categorical_cols = df.select_dtypes(include='object').columns
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

X = df_encoded.drop('status_Placed', axis=1)
y = df_encoded['status_Placed']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

gender_test = df.loc[X_test.index, 'gender']

parity_df = pd.DataFrame({
    'actual': y_test,
    'predicted': y_pred,
    'gender': gender_test
})

male_predictions = parity_df[parity_df['gender'] == 'M']['predicted']
female_predictions = parity_df[parity_df['gender'] == 'F']['predicted']

male_proportion = male_predictions.mean()
female_proportion = female_predictions.mean()

demographic_parity_difference = abs(male_proportion - female_proportion)

print(f"Proportion of positive predictions for Males: {male_proportion:.4f}")
print(f"Proportion of positive predictions for Females: {female_proportion:.4f}")
print(f"Demographic parity difference (Absolute): {demographic_parity_difference:.4f}")

'''
Mathematically:
𝑃(𝑌̂ = 1|𝐴 = 0) = 𝑃(𝑌̂ = 1|𝐴 = 1)
where
• 𝑌̂= model prediction,
• 𝐴= sensitive attribute (e.g., gender or race)
Results showed a DP Difference of 0.03167, revealing a slight bias favoring Males over
Females in loan approval predictions.
'''