# -*- coding: utf-8 -*-
"""DP-Laplace8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7BiLPNnwLp_A9mwic44Gz-LSlCCuZSQ
"""

import pandas as pd
from sklearn.datasets import load_wine

wine = load_wine()
df = pd.DataFrame(data=wine.data, columns=wine.feature_names)

import numpy as np

def add_laplace_noise(value, sensitivity, epsilon):
  """Adds Laplace noise to a given value.

  Args:
    value: The value to which noise will be added.
    sensitivity: The sensitivity of the query.
    epsilon: The privacy parameter epsilon.

  Returns:
    The noisy value.
  """
  b = sensitivity / epsilon
  noise = np.random.laplace(loc=0, scale=b)
  return value + noise

# 1. Choose a column
column_to_count = 'alcohol'

# 2. Calculate the true count
true_count = df[column_to_count].count()

# 3. Determine sensitivity (sensitivity for count query is 1)
sensitivity = 1

# 4. Choose a value for epsilon
epsilon = 1.0

# 5. Apply the add_laplace_noise function
noisy_count = add_laplace_noise(true_count, sensitivity, epsilon)

# 6. Store the noisy count (already done in step 5)

# 7. Print the true count and the noisy count
print(f"True count of '{column_to_count}': {true_count}")
print(f"Noisy count of '{column_to_count}' (epsilon={epsilon}): {noisy_count}")
# Shashank Rautkar Prn:20220802284

# 1. Choose a numerical column
column_to_mean = 'alcohol'

# 2. Calculate the true mean
true_mean = df[column_to_mean].mean()

# 3. Determine the sensitivity for the mean query
data_range = df[column_to_mean].max() - df[column_to_mean].min()
sensitivity_mean = data_range / len(df)

# 4. Choose a value for epsilon (using the same value as for the count query)
epsilon_mean = epsilon # Using the epsilon from the previous step

# 5. Apply the add_laplace_noise function
noisy_mean = add_laplace_noise(true_mean, sensitivity_mean, epsilon_mean)

# 6. Print the true mean and the noisy mean
print(f"True mean of '{column_to_mean}': {true_mean}")
print(f"Noisy mean of '{column_to_mean}' (epsilon={epsilon_mean}): {noisy_mean}")
# Shashank Rautkar Prn:20220802284

'''
Differential Privacy (DP) provides a formal guarantee that the removal or addition of a single
record does not significantly change the output of a function or analysis.
It achieves this by adding random noise to query results.

To measure the privacy–accuracy trade-off based on noise scale (ε).

At ε = 1.0, the result (~₹180) nearly matches the true value, balancing privacy and
accuracy. You can change epsilon. As ε (epsilon) increases, noise decreases,
and accuracy improves — at the expense of privacy strength.