# -*- coding: utf-8 -*-
"""LIME5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pj_Q0TrfkNZqQlD4Ub8q5OWf-zBCjLhV
"""

#Local Interpretability and Explanation of Model Predictions Using LIME.
!pip install lime

# Mauli Kangude - 2149
# Lab 5 - Local Model Explanations using LIME

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from lime.lime_tabular import LimeTabularExplainer

# 1. Load and preprocess data
data = pd.read_csv("Loan.csv")

le = LabelEncoder()
for col in ['Gender', 'Education', 'Married']:
    data[col] = le.fit_transform(data[col].astype(str))

# Impute missing values for numerical columns before splitting and scaling
data['LoanAmount'].fillna(data['LoanAmount'].mean(), inplace=True)
data['Credit_History'].fillna(data['Credit_History'].mode()[0], inplace=True)

X = data[['ApplicantIncome', 'Gender', 'Education', 'Credit_History', 'LoanAmount']]
y = data['Loan_Status']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2. Train model
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.3,
    random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# 3. Initialize LIME explainer
explainer = LimeTabularExplainer(
    training_data=X_train,
    feature_names=X.columns,
    class_names=['Not Approved', 'Approved'],
    mode='classification'
)

# 4. Pick a random test instance
i = np.random.randint(0, len(X_test))
exp = explainer.explain_instance(
    X_test[i],
    model.predict_proba,
    num_features=6
)

# 5. Display explanation
exp.show_in_notebook(show_table=True)
exp.save_to_file('lime_explanation.html')

'''
Credit_History were the two strongest positive contributors,
significantly increasing the likelihood of approval.

Gender had a minimal effect showing a small residual bias but not
dominant.

• The final decision is moderately confident (≈ 83% probability).