# -*- coding: utf-8 -*-
"""PotenialBias3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jimMZS7RwiWiPqq2EYDMhDzwOzqJPYiM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("Loan.csv")

# Quick overview
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.head())

print("Missing Values:\n", df.isnull().sum())

# Convert Loan_Status to numeric for analysis (only if present)
if "Loan_Status" in df.columns:
    df["Loan_Status"] = df["Loan_Status"].map({"Y": 1, "N": 0})

# 3. Define sensitive features

sensitive_features = ["Gender", "Married", "Education", "Self_Employed", "Property_Area"]
outcome_var = "Loan_Status"

# Keep only sensitive features that exist in the dataframe
sensitive_features = [f for f in sensitive_features if f in df.columns]

print("\n--- Sample Bias: Group Representation ---")
for feat in sensitive_features:
    print(f"\n{feat} distribution (%):")
    print((df[feat].value_counts(normalize=True) * 100).round(2))

    plt.figure(figsize=(6,4))
    sns.countplot(x=feat, data=df, hue=feat, palette="pastel", legend=False)
    plt.title(f"{feat} Distribution")
    plt.xticks(rotation=30)
    plt.show()

print("\n--- Measurement Bias: Missing Data by Group ---")

cols_with_missing = [c for c in df.columns if df[c].isnull().any()]

for feat in sensitive_features:
    print(f"\nMissing value rate by {feat}:")
    if cols_with_missing:
        print(df.groupby(feat)[cols_with_missing].apply(lambda x: x.isnull().mean()))
    else:
        print("No missing values in dataframe.")

# 7. Correlation Heatmap (Numeric Features)
# ------------------------------
num_df = df.select_dtypes(include=[np.number])
if not num_df.empty:
    plt.figure(figsize=(10,8))
    sns.heatmap(num_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
    plt.title("Correlation Heatmap of Numeric Features")
    plt.show()
else:
    print("\nNo numeric columns to compute correlation heatmap.")

print("\n--- Summary of Findings ---")
for feat in sensitive_features:
    if feat in df.columns and outcome_var in df.columns:
        rates = df.groupby(feat)[outcome_var].mean()
        print(f"{feat}: approval rate range {rates.min():.2f}–{rates.max():.2f}")
        counts = df[feat].value_counts(normalize=True)
        under = counts[counts < 0.05]
        if len(under) > 0:
            print("Underrepresented groups (<5%):")
            print(under.round(3))
        print()
    elif feat in df.columns:
        print(f"{feat}: (outcome variable '{outcome_var}' not available for approval rate calculation)\n")

print("Bias detection complete.")

'''
identified potential bias indicators in historical loan data by
comparing approval rates across demographic categories.
correlation matrix confirms that approvals are influenced primarily by credit
score

'''