# -*- coding: utf-8 -*-
"""SHAP6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_q-5EmQXsbvhkdeH7QYg_2B4jHCSHPGV
"""

!pip install shap

import pandas as pd
import shap
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt

# Load dataset
data = pd.read_csv("Loan.csv")

# Encode categorical features
le = LabelEncoder()
for col in ['Gender', 'Education', 'Married']:
    data[col] = le.fit_transform(data[col].astype(str))

# Define features and target
X = data[['ApplicantIncome', 'Gender', 'Education',
          'Credit_History', 'LoanAmount']]
y = data['Loan_Status']

# Impute missing values before scaling
X['LoanAmount'] = X['LoanAmount'].fillna(X['LoanAmount'].median())
X['Credit_History'] = X['Credit_History'].fillna(X['Credit_History'].mode()[0])

# Scale and split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42
)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Initialize SHAP explainer
explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test)

# Convert X_test back to DataFrame with column names
X_test_df = pd.DataFrame(X_test, columns=X.columns)

# --- Visualization 1: SHAP Summary Plot ---
shap.summary_plot(
    shap_values,
    features=X_test_df,
    feature_names=X_test_df.columns
)

# --- Visualization 2: SHAP Bar Plot (Mean Absolute SHAP values) ---
shap.summary_plot(
    shap_values,
    features=X_test_df,
    feature_names=X_test_df.columns,
    plot_type="bar"
)

'''
Credit_History
Biggest positive impact. Good credit history increases loan approval.

ApplicantIncome
Higher income increases approval chance.

LoanAmount
Large loan amount reduces approval probability.

Education
Moderate effect. Slight improvement for higher education.

Married
Small demographic influence.

Gender
Very minimal effect. Almost no impact on approval.

SHAP-based global analysis clearly identified credit score and income as the most
influential drivers of loan approval

