# -*- coding: utf-8 -*-
"""XAI-BOTH7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJVpLStx_rxXQUO1N-HQ5NGPHLvsygDN
"""

!pip install shap
!pip install lime

import pandas as pd
import numpy as np
import shap
from lime.lime_tabular import LimeTabularExplainer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load and preprocess dataset
data = pd.read_csv("Loan.csv")

# Handle missing values in numerical columns
data['LoanAmount'].fillna(data['LoanAmount'].mean(), inplace=True)
# Credit_History is often binary (1.0 or 0.0), so mode imputation is suitable.
data['Credit_History'].fillna(data['Credit_History'].mode()[0], inplace=True)

le = LabelEncoder()
for col in ['Gender', 'Education', 'Married']:
    data[col] = le.fit_transform(data[col].astype(str))

X = data[['ApplicantIncome', 'Gender', 'Education', 'Married',
          'Credit_History', 'LoanAmount']]

# Encode the target variable 'Loan_Status'
data['Loan_Status'] = le.fit_transform(data['Loan_Status'])
y = data['Loan_Status']

# Scale and split data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42
)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# --- SHAP Global Analysis ---
explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test)
shap.summary_plot(
    shap_values,
    features=pd.DataFrame(X_test, columns=X.columns),
    feature_names=X.columns
)

# --- Identify correlated features with sensitive attributes ---
corr_matrix = pd.DataFrame(X, columns=X.columns).corr()[['Gender', 'Married']].round(2)
print("Correlation of Sensitive features:\n", corr_matrix)

# --- LIME Local Analysis for one instance ---
explainer_lime = LimeTabularExplainer(
    training_data=X_train,
    feature_names=X.columns,
    class_names=['Not Approved', 'Approved'],
    mode='classification'
)

i = np.random.randint(0, len(X_test))
exp = explainer_lime.explain_instance(
    X_test[i],
    model.predict_proba,
    num_features=6
)
exp.show_in_notebook(show_table=True)
exp.save_to_file('lime_explanation.html')

'''
SHAP:
Shows global feature importance. Credit history and income strongly increase approval. High loan amount reduces approval. Demographic features have very small effect.

Correlation Check:
Sensitive features like gender and marital status show low correlation with other fields. No major indirect bias.

LIME:
Explains one specific prediction. Highlights which features pushed the decision up or down for that single loan case.

Conclusion:
The model mostly relies on financial factors, not sensitive attributes. Predictions are transparent and reasonably fair.